sender:
  - "gabrieleoliveto26@gmail.com"

recipients:
  - "gabrieleoliveto26@gmail.com"
  
app_password:
  - "kuydqcoafjidqowr"

assembly_codes:
 - hg38

gencode_versions:
 - "49"

tss_subsets:
 - pc

sample_types:
 - N
 
distances:
 - 50000

min_CpGs:
 - 50

leftCount_betas:
  - 0.4

rightCount_betas:
  - 0.6

minCount_exprs:
  - 20

minSamples_betas:
  - 90

minCovs:
  - 10

minSamples_exprs:
  - 10
  
Ks:
  - 100

importances:
  - "shap"

selected_txIDs_location:
  - "resources/TxIDs/selected_TxIDs"

use_TMRs:
  - 0

TMRs_dir:
  - "resources/CpG_data/TMRs/"