assembly_codes:
 - hg38

gencode_versions:
 - 49

current_dates:
 - 20251016

tss_subsets:
 - pc

comparison_types:
 - NT

sample_types:
 - N
 
distances:
 - 50000

min_CpGs:
 - 5

leftCount_betas:
  - 0.4

rightCount_betas:
  - 0.6

minCount_exprs:
  - 20

minSamples_betas:
  - 90

minCovs:
  - 10

minSamples_exprs:
  - 10
  
Ks:
  - 100

selected_txIDs_location:
  - "resources/TxIDs/cancerGeneList_processed.tsv"
  