sender:
  - "gabrieleoliveto26@gmail.com"

recipients:
  - "gabrieleoliveto26@gmail.com"
  
app_password:
  - "kuydqcoafjidqowr"

assembly_codes:
 - hg38

gencode_versions:
 - "38"

tss_subsets:
 - pc

sample_types:
 - T
 
distances:
 - 250000

min_CpGs:
 - 50

leftCount_betas:
  - 0.4

rightCount_betas:
  - 0.6

minCount_exprs:
  - 20

minSamples_betas:
  - 90

minCovs:
  - 10

minSamples_exprs:
  - 10
  
Ks:
  - 100

importances:
  - "shap"

selected_txIDs_location:
  - "resources/TxIDs/selected_TxIDs"

TMRs_dir:
  - "resources/TMRs"

use_TMRs:
  - 0

n_jobs_xgboost:
  - 5

n_jobs_sklearn:
  - 1

n_iter_rsearch:
  - 27

verbosity:
  - 0

num_features_threshold:
  - 23

hypertune_random_state_rsearch:
  - 21


