sender:
  - "gabrieleoliveto26@gmail.com"

recipients:
  - "gabrieleoliveto26@gmail.com"
  - "alessandro.vitriolo@ieo.it"
  
app_password:
  - "kuydqcoafjidqowr"

assembly_codes:
 - hg38

gencode_versions:
 - "49"

tss_subsets:
 - pc

comparison_types:
 - NT

sample_types:
 - N
 
distances:
 - 500000

min_CpGs:
 - 5

leftCount_betas:
  - 0.5

rightCount_betas:
  - 0.5

minCount_exprs:
  - 20

minSamples_betas:
  - 90

minCovs:
  - 10

minSamples_exprs:
  - 10
  
Ks:
  - 100

selected_txIDs_location:
  - "resources/TxIDs/cancerGeneList_processed.tsv"

importances:
  - "shap"
