sender:
  - "gabrieleoliveto26@gmail.com"

recipients:
  - "gabrieleoliveto26@gmail.com"
  
app_password:
  - "kuydqcoafjidqowr"

assembly_codes:
 - hg38

gencode_versions:
 - "38"

tss_subsets:
 - pc

sample_types:
 - N
 
distances:
 - 500000

slop_distances:
 - 100000

min_CpGs:
 - 50

K_closests:
 - 5000

leftCount_betas:
  - 0.5

rightCount_betas:
  - 0.5

minCount_exprs:
  - 25

minSamples_betas:
  - 90

minCovs:
  - 10

minSamples_exprs:
  - 10

importances:
  - "shap"

selected_txIDs_location:
  - "resources/TxIDs/selected_TxIDs"

TMRs_dir:
  - "resources/TMRs"

use_TMRs:
  - 1

n_jobs_xgboost:
  - 10

n_jobs_sklearn:
  - 1

n_iter_rsearch:
  - 27

verbosity:
  - 0

num_features_threshold:
  - 23

hypertune_random_state_rsearch:
  - 21

test_sizes:
  - 0.3

CVs:
  - 5
